config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/components', to: "pages#components"

  resources :schools, only: %i[index show new create] do
    resources :school_menus, only: %i[index new create]
  end

  resources :school_menus, only: %i[show] do
    resources :menus, only: %i[index new create]
  end

  resources :menus, only: %i[show] do
    resources :day_dishes, only: %i[index show]
  end

  resources :day_dishes, only: %i[] do
    resources :dish, only: %i[index show]
  end

  resources :profiles, except: %i[delete] do
    resources :profile_allergies, except: %i[delete]
  end

  resources :profile_allergies, only: %i[] do
    resources :ingredients, except: %i[delete]
  end

  resources :ingredients, only: %i[] do
    resources :dish_ingredients, only: %i[index show]
  end

  resources :dishes, only: %i[index show]
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

# dish ingreditents should be via ingredients
# when listed first include 'only', when listed second include 'excepet'

app/views/shared/_card_menu.html.erb
<h1><%= @menu.school_menu.date.strftime("%d %B '%y") %> - <%= (@menu.school_menu.date + 18).strftime("%d %B '%y") %> </h1>
  <br><br>
    <% @menus_in_week.each do |menu| %>
      <h3><%= menu.menu_date.strftime("%A") %></h3>
        <div class="cards">
          <% menu.dishes.each do |dish| %>
            <div class="card">
              <div class="card-body">
                <br>
                <h3 class="card-title"> <%= dish.name %> </h3>
                <br>
              </div>
            </div>
          <% end %>
        </div>
      <br><br>
    <% end %>

app/views/shared/_card_school-menu.html.erb
<section>
  <h3 class="card-title">
    <div class="justify-content-between d-flex">
      <div>
        <%= @first_school_menu.date.strftime("%d %B '%y") %> - <%= (@first_school_menu.date + 4).strftime("%d %B '%y") %>
      </div>
      <div>
        <%= link_to "Create new menu",  new_school_menu_menu_path(@first_school_menu), class: "btn btn-primary"%>
      </div>
    </div>
  </h3>
  <br>
  <br>

  <div class="cards">
    <% @first_week_menus.where(tailored: true).each do |menu| %>
      <div class="card">
        <div class="card-body">
          <br>
          <%# <p class="card-text"><%= school.postcode %>
            <%# <h3><%= menu.profile.profile_allergies.first.ingredient.name %>
            <h3><% menu.profile.profile_allergies.each do |profile_allergy| %>
              <%= profile_allergy.ingredient.name.capitalize %>
            <% end %> free </h3>

          <%# <% raise %>
          <div>
            <br>
            <%= link_to "View menu", menu_path(menu), class: "btn btn-outline-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

<br>
<br>
<br>

app/views/shared/_card_school.html.erb
 <div class="cards">
  <% @schools.each do |school| %>
    <div class="card">
      <div class="card-body">
        <%= cl_image_tag school.photo.key, class:"avatar-large"%>
        <br><br>
        <h3 class="card-title"><%= school.name %></h3>
        <p class="card-text"><%= school.postcode %></p>
        <div>
          <br>
          <%= link_to "View menus", school_path(school.id), class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon"
        data-controller="navbar"
        data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">

    <% if user_signed_in? %>
      <%= link_to schools_path, class: "navbar-brand" do %>
        <%= image_tag "logoimg.png", class:"logo" %>
      <% end %>
    <% else %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logoimg.png", class:"logo" %>
      <% end %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
         <ul class="navbar-nav ml-auto">
            <%= link_to 'Dashboard', schools_path, class:"btn btn-link" %>
          </li>
          <li>
            <%= link_to 'Add a School', new_school_path, class: 'btn btn-primary' %>
          </li>
          <%# <li class="nav-item dropdown"> %>
            <ul class="navbar-nav ml-auto">
            <%= image_tag "clairesister.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
         <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <br>
          <li class="nav-item">
            <%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/old_card_school_menu.html.erb
  <div class="cards">
    <% @school.school_menus.each do |school_menu| %>
      <div class="card">
        <div class="card-body">
          <br>
          <h3 class="card-title"><%= school_menu.date.strftime("%d %B '%y") %> - <%= (school_menu.date + 18).strftime("%d %B '%y") %> </h3>
          <%# <p class="card-text"><%= school.postcode %>
          <div>
            <br>
            <%= link_to "View menu", school_menu_path(school_menu), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<br>
<br>
<br>
<br>